#!/usr/bin/env python3

from time import sleep
from os.path import expanduser
import os
import sys
from datetime import datetime
import curses
from bleson import get_provider, Observer, UUID16
from bleson.logger import log, set_level, ERROR, DEBUG
import json

home = expanduser("~")
f_config = home + "/.goveewatch.conf"

# Disable warnings
set_level(ERROR)

# # Uncomment for debug log level
# set_level(DEBUG)

# https://macaddresschanger.com/bluetooth-mac-lookup/A4%3AC1%3A38
# OUI Prefix	Company
# A4:C1:38	Telink Semiconductor (Taipei) Co. Ltd.
GOVEE_BT_mac_OUI_PREFIX = "A4:C1:38"

H5075_UPDATE_UUID16 = UUID16(0xEC88)

govee_devices = {}
known_devices = {}

# ###########################################################################
FORMAT_PRECISION = ".2f"


# Decode H5075 Temperature into degrees Celcius
def decode_temp_in_c(encoded_data):
    return format((encoded_data / 10000), FORMAT_PRECISION)


# Decode H5075 Temperature into degrees Fahrenheit
def decode_temp_in_f(encoded_data):
    return format((((encoded_data / 10000) * 1.8) + 32), FORMAT_PRECISION)


# Decode H5075 percent humidity
def decode_humidity(encoded_data):
    return format(((encoded_data % 1000) / 10), FORMAT_PRECISION)


def print_values(mac):
    govee_device = govee_devices[mac]
    print(
        f"{govee_device['name']} ({govee_device['address']}) - \
Temperature {govee_device['tempInC']}C / {govee_device['tempInF']}F  - \
Humidity: {govee_device['humidity']}% - \
Battery:  {govee_device['battery']}%"
    )


def print_rssi(mac):
    govee_device = govee_devices[mac]
    print(
        f"{govee_device['name']} ({govee_device['address']}) - \
RSSI: {govee_device['rssi']}"
    )


# On BLE advertisement callback
def on_advertisement(advertisement):
    log.debug(advertisement)

    if advertisement.address.address.startswith(GOVEE_BT_mac_OUI_PREFIX):
        mac = advertisement.address.address
        if mac not in govee_devices:
            govee_devices[mac] = {}
    
        if H5075_UPDATE_UUID16 in advertisement.uuid16s:
            # HACK:  Proper decoding is done in bleson > 0.10
            name = advertisement.name.split("'")[0]
            encoded_data = int(advertisement.mfg_data.hex()[6:12], 16)
            battery = int(advertisement.mfg_data.hex()[12:14], 16)
            govee_devices[mac]["address"] = mac
            govee_devices[mac]["name"] = name
            govee_devices[mac]["mfg_data"] = advertisement.mfg_data
            govee_devices[mac]["data"] = encoded_data

            govee_devices[mac]["tempInC"] = decode_temp_in_c(encoded_data)
            govee_devices[mac]["tempInF"] = decode_temp_in_f(encoded_data)
            govee_devices[mac]["humidity"] = decode_humidity(encoded_data)
            govee_devices[mac]["battery"] = str(battery).rjust(3, ' ')
            now = datetime.now()
            govee_devices[mac]["timestamp"] = now
            # print_values(mac)

        if advertisement.rssi is not None and advertisement.rssi != 0:
            govee_devices[mac]["rssi"] = advertisement.rssi
            # print_rssi(mac)

        log.debug(govee_devices[mac])

# ###########################################################################

if not os.path.isfile(f_config):
    print("Configuration file not found")
    print("Generating empty configuration file: " + f_config)
    text_file = open(f_config, "w")
    text_file.write('{')
    text_file.write('\n\t\"devices\":[')
    text_file.write('\n\t]')
    text_file.write('\n}')
    text_file.close()
    exit(1)
with open(f_config) as conf:
    data = json.load(conf)
    for entry in data["devices"]:
        known_devices[entry["name"]] = entry["alias"] 

limit_temperature_low  = float(data["thresholds"]["temp low"])
limit_temperature_high = float(data["thresholds"]["temp high"])
limit_humidity_low     = float(data["thresholds"]["humidity low"])
limit_humidity_high    = float(data["thresholds"]["humidity high"])

adapter = get_provider().get_adapter()
observer = Observer(adapter)
observer.on_advertising_data = on_advertisement

stdscr = curses.initscr()
rows, columns = stdscr.getmaxyx()

curses.curs_set(0)
curses.noecho()
curses.start_color()
curses.use_default_colors()

style_normal = curses.color_pair(0)
style_low    = curses.color_pair(25) | curses.A_BOLD
style_high   = curses.color_pair(2)  | curses.A_BOLD

for i in range(0, curses.COLORS):
        curses.init_pair(i + 1, i, -1)

'''
try:
    for i in range(0, 255):
        stdscr.addstr(str(i), curses.color_pair(i))
except curses.ERR:
    # End of screen reached
    pass
    stdscr.getch()
'''

try:
    while True:
        observer.start()
        sleep(0.5)
        observer.stop()

        rows_new, columns_new = stdscr.getmaxyx()

        if rows_new != rows or columns_new != columns:
            stdscr.clear()

        rows = rows_new
        columns = columns_new

        line = 0

        stdscr.addstr(line, 0, "Mac Address", curses.color_pair(0) | curses.A_BOLD)
        stdscr.addstr(line,20, "Location"   , curses.color_pair(0) | curses.A_BOLD)
        stdscr.addstr(line,42, "Temperature", curses.color_pair(0) | curses.A_BOLD)
        stdscr.addstr(line,55, "Humidity"   , curses.color_pair(0) | curses.A_BOLD)
        stdscr.addstr(line,65, "Battery"    , curses.color_pair(0) | curses.A_BOLD)
        stdscr.addstr(line,75, "Last seen"  , curses.color_pair(0) | curses.A_BOLD)

        for key, value in govee_devices.items():
            line = line + 1
            stdscr.move(line, 0)
            stdscr.clrtoeol()
            stdscr.move(line, 0)

            stdscr.addstr(line, 0, key)
            if value["name"] in known_devices.keys():
                stdscr.addstr(line,20, known_devices[value["name"]])
            else:
                stdscr.addstr(line,20, value["name"])

            temp = float(value["tempInC"])
            humidity = float(value["humidity"])

            style_temperature = style_normal
            style_humidity    = style_normal


            if temp < limit_temperature_low :
                style_temperature = style_low

            if temp > limit_temperature_high :
                style_temperature = style_high

            if humidity < limit_humidity_low :
                style_humidity = style_low

            if humidity > limit_humidity_high :
                style_humidity = style_high

            stdscr.addstr(line,42, value["tempInC"] + " \u00b0", style_temperature)
            stdscr.addstr(line,55, value["humidity"] + '%', style_humidity)
            stdscr.addstr(line,65, value["battery"] + '%')
            stdscr.addstr(line,73, str((datetime.now() - value["timestamp"]).seconds).rjust(4) + " seconds ago")
        stdscr.refresh()

except KeyboardInterrupt:
    observer.stop()
    curses.curs_set(1)
    curses.echo()
    curses.endwin()
    curses.reset()
    sys.exit(0)
